openapi: 3.0.0
info:
  title: Contact API Spec
  description: Contact API Spec
  version: 1.0.0
servers:
  - url: 'http://localhost:8181/api/contacts'
paths:
  /:
    post:
      summary: "Create Contact"
      parameters:
        - $ref: "#/components/parameters/X-API-TOKEN"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contact"
            examples:
              Contact:
                $ref: "#/components/examples/contact-example"

      responses:
        201:
          $ref: "#/components/responses/GeneralSuccessResponse"
        400:
          $ref: "#/components/responses/GeneralBadRequestResponse"
        401:
          $ref: "#/components/responses/UnauthorizedErrorResponse"
        500:
          $ref: "#/components/responses/ServerErrorResponse"
    get:
      summary: "Search Contacts"
      parameters:
        - $ref: "#/components/parameters/X-API-TOKEN"
        - in: query
          name: name
          description: "Search contact by first name or last name"
          schema:
            type: string
        - in: query
          name: phone
          description: "Search contact by phone number"
          schema:
            type: string
        - in: query
          name: email
          description: "Search contact by email address"
          schema:
            type: string
        - in: query
          name: page
          description: "Current page number"
          schema:
            type: integer
            default: 0
        - in: query
          name: size
          description: "Maximum data contact we need"
          schema:
            type: integer
            default: 10

      responses:
        200:
          description: "Success get contacts"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/contact"
                  paging:
                    type: object
                    properties:
                      currentPage:
                        type: integer
                      totalPage:
                        type: integer
                      sizePerPage:
                        type: integer
              example:
                data:
                  - id: "random-string"
                    firstName: "John"
                    lastName: "Doe"
                    email: "johndoe@example.com"
                    phone: "089999000"
                paging:
                  currentPage: 0
                  totalPage: 10
                  sizePerPage: 10
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
              example:
                errors: "Query parameter is invalid"
        401:
          $ref: "#/components/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/components/responses/ContactIsNotFoundErrorResponse"
        500:
          $ref: "#/components/responses/ServerErrorResponse"
  /{idContact}:
    put:
      summary: "Update contact"
      parameters:
        - $ref: "#/components/parameters/X-API-TOKEN"
        - $ref: "#/components/parameters/ID-CONTACT-PATH"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contact"
            examples:
              Contact:
                $ref: "#/components/examples/contact-example"
      responses:
        200:
          $ref: "#/components/responses/GeneralSuccessResponse"
        400:
          $ref: "#/components/responses/GeneralBadRequestResponse"
        401:
          $ref: "#/components/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/components/responses/ContactIsNotFoundErrorResponse"
        500:
          $ref: "#/components/responses/ServerErrorResponse"
    get:
      summary: "Get a contact"
      parameters:
        - $ref: "#/components/parameters/X-API-TOKEN"
        - $ref: "#/components/parameters/ID-CONTACT-PATH"
      responses:
        200:
          $ref: "#/components/responses/GeneralSuccessResponse"
        401:
          $ref: "#/components/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/components/responses/ContactIsNotFoundErrorResponse"
        500:
          $ref: "#/components/responses/ServerErrorResponse"
    delete:
      summary: "Delete a contact"
      parameters:
        - $ref: "#/components/parameters/X-API-TOKEN"
        - $ref: "#/components/parameters/ID-CONTACT-PATH"
      responses:
        200:
          description: "Success delete the contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
              example:
                data: "OK"
        401:
          $ref: "#/components/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/components/responses/ContactIsNotFoundErrorResponse"
        500:
          $ref: "#/components/responses/ServerErrorResponse"


components:
  schemas:
    contact:
      required:
        - firstName
        - email
        - phone
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
    GeneralError:
      type: object
      properties:
        errors:
          type: string
  examples:
    contact-example:
      description: "Contact example"
      value:
        firstName: "John"
        lastName: "Doe"
        email: "johndoe@example.com"
        phone: "089999000"
    response-contact-example:
      value:
        data:
          id: "random-string"
          firstName: "John"
          lastName: "Doe"
          email: "johndoe@example.com"
          phone: "089999000"
  parameters:
    X-API-TOKEN:
      name: "X-API-TOKEN"
      in: "header"
      required: true
      description: "auth token"
      schema:
        type: string
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    ID-CONTACT-PATH:
      name: idContact
      in: path
      required: true
      example: "random-string"
  responses:
    GeneralSuccessResponse:
      description: "Success response"
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "#/components/schemas/contact"
    GeneralBadRequestResponse:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
          examples:
            InvalidData:
              value:
                errors: "Email format invalid, phone format invalid, ..."
            DuplicateName:
              value:
                errors: "First name and Last name is already use"

    UnauthorizedErrorResponse:
      description: "Unauthorized request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
          example:
            errors: "Unauthorized request"
    ContactIsNotFoundErrorResponse:
      description: "Content is not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
          example:
            errors: "Contact is not found"
    ServerErrorResponse:
      description: "Server error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
          example:
            errors: "Server unavailable, try again"